# -*- coding: utf-8 -*-
"""Importação Números lemit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfY4fGAaSNd4-hsH107clpITtCEGJp0I
"""

import pandas as pd
import smtplib
import numpy as np
from email.message import EmailMessage
from datetime import datetime, date
from dateutil.relativedelta import relativedelta

d_types = {'NOME':str, 'CPF/CNPJ':str, 'TIPO-LOGRADOURO':str, 'FULL-LOGRADOURO':str, 'NUMERO':str, 'COMPLEMENTO':str, 'BAIRRO':str, 'CIDADE':str, 'UF':str, 'CEP':str,
           'TIPO-LOGRADOURO.1':str, 'FULL-LOGRADOURO.1':str, 'NUMERO.1':str, 'COMPLEMENTO.1':str,'BAIRRO.1':str,'CIDADE.1':str,'UF.1':str,'CEP.1':str,
           'TIPO-LOGRADOURO.2':str,'FULL-LOGRADOURO.2':str,'NUMERO.2':str,'COMPLEMENTO.2':str,'BAIRRO.2':str,'CIDADE.2':str,'UF.2':str,'CEP.2':str,
           'TIPO-LOGRADOURO.3':str,'FULL-LOGRADOURO.3':str,'NUMERO.3':str,'COMPLEMENTO.3':str,'BAIRRO.3':str,'CIDADE.3':str,'UF.3':str,'CEP.3':str,
           'DDD':str,'FONE':str,'TIPO-FONE':str,'RANKING':str,'SCORE':str,'POSSUI-WHATSAPP':str,
           'DDD.1':str,'FONE.1':str,'TIPO-FONE.1':str,'RANKING.1':str,'SCORE.1':str,'POSSUI-WHATSAPP.1':str,
           'DDD.2':str,'FONE.2':str,'TIPO-FONE.2':str,'RANKING.2':str,'SCORE.2':str,'POSSUI-WHATSAPP.2':str,
           'DDD.3':str,'FONE.3':str,'TIPO-FONE.3':str,'RANKING.3':str,'SCORE.3':str,'POSSUI-WHATSAPP.3':str,
           'DDD.4':str,'FONE.4':str,'TIPO-FONE.4':str,'RANKING.4':str,'SCORE.4':str,'POSSUI-WHATSAPP.4':str,
           'DDD.5':str,'FONE.5':str,'TIPO-FONE.5':str,'RANKING.5':str,'SCORE.5':str,'POSSUI-WHATSAPP.5':str,
           'DDD.6':str,'FONE.6':str,'TIPO-FONE.6':str,'RANKING.6':str,'SCORE.6':str,'POSSUI-WHATSAPP.6':str,
           'DDD.7':str,'FONE.7':str,'TIPO-FONE.7':str,'RANKING.7':str,'SCORE.7':str,'POSSUI-WHATSAPP.7':str,
           'EMAIL-1':str,'EMAIL-2':str,'EMAIL-3':str}

df = pd.read_csv(
    'base.csv',
    delimiter=';',  # Caso o delimitador no CSV seja diferente (por exemplo, ponto e vírgula)
    header=0,       # Usa a primeira linha do arquivo como nomes das colunas
    encoding='utf-8' # Define a codificação dos caracteres
    ,dtype=d_types
)

d_type2 = {'CPF/CNPJ':str,
           'NUMERO':str,
           'ATIVO':str}

df_num = pd.read_excel('base_num.xlsx',sheet_name='Telefones',dtype=d_type2)
df_num1 = df_num[['CPF/CNPJ','NUMERO','ATIVO']]
df_num1['CHAVE'] = df_num1['CPF/CNPJ'].astype(str) + '-' + df_num1['NUMERO'].astype(str)

base1 = df[['NOME', 'CPF/CNPJ','DDD', 'FONE', 'TIPO-FONE','RANKING', 'SCORE', 'POSSUI-WHATSAPP']]
base2 = df[['NOME', 'CPF/CNPJ','DDD.1', 'FONE.1', 'TIPO-FONE.1','RANKING.1', 'SCORE.1', 'POSSUI-WHATSAPP.1']]
base3 = df[['NOME', 'CPF/CNPJ','DDD.2', 'FONE.2','TIPO-FONE.2', 'RANKING.2', 'SCORE.2', 'POSSUI-WHATSAPP.2']]
base4 = df[['NOME', 'CPF/CNPJ','DDD.3','FONE.3', 'TIPO-FONE.3', 'RANKING.3', 'SCORE.3', 'POSSUI-WHATSAPP.3']]
base5 = df[['NOME', 'CPF/CNPJ','DDD.4', 'FONE.4', 'TIPO-FONE.4', 'RANKING.4', 'SCORE.4','POSSUI-WHATSAPP.4']]
base6 = df[['NOME', 'CPF/CNPJ','DDD.5', 'FONE.5', 'TIPO-FONE.5', 'RANKING.5','SCORE.5', 'POSSUI-WHATSAPP.5']]
base7 = df[['NOME', 'CPF/CNPJ','DDD.6', 'FONE.6', 'TIPO-FONE.6','RANKING.6', 'SCORE.6', 'POSSUI-WHATSAPP.6']]
base8 = df[['NOME', 'CPF/CNPJ','DDD.7', 'FONE.7','TIPO-FONE.7', 'RANKING.7', 'SCORE.7', 'POSSUI-WHATSAPP.7']]
#
base2 = base2.rename(columns={'DDD.1': 'DDD', 'FONE.1': 'FONE', 'TIPO-FONE.1': 'TIPO-FONE','RANKING.1': 'RANKING', 'SCORE.1': 'SCORE', 'POSSUI-WHATSAPP.1': 'POSSUI-WHATSAPP'})
base3 = base3.rename(columns={'DDD.2': 'DDD', 'FONE.2': 'FONE', 'TIPO-FONE.2': 'TIPO-FONE','RANKING.2': 'RANKING', 'SCORE.2': 'SCORE', 'POSSUI-WHATSAPP.2': 'POSSUI-WHATSAPP'})
base4 = base4.rename(columns={'DDD.3': 'DDD', 'FONE.3': 'FONE', 'TIPO-FONE.3': 'TIPO-FONE','RANKING.3': 'RANKING', 'SCORE.3': 'SCORE', 'POSSUI-WHATSAPP.3': 'POSSUI-WHATSAPP'})
base5 = base5.rename(columns={'DDD.4': 'DDD', 'FONE.4': 'FONE', 'TIPO-FONE.4': 'TIPO-FONE','RANKING.4': 'RANKING', 'SCORE.4': 'SCORE', 'POSSUI-WHATSAPP.4': 'POSSUI-WHATSAPP'})
base6 = base6.rename(columns={'DDD.5': 'DDD', 'FONE.5': 'FONE', 'TIPO-FONE.5': 'TIPO-FONE','RANKING.5': 'RANKING', 'SCORE.5': 'SCORE', 'POSSUI-WHATSAPP.5': 'POSSUI-WHATSAPP'})
base7 = base7.rename(columns={'DDD.6': 'DDD', 'FONE.6': 'FONE', 'TIPO-FONE.6': 'TIPO-FONE','RANKING.6': 'RANKING', 'SCORE.6': 'SCORE', 'POSSUI-WHATSAPP.6': 'POSSUI-WHATSAPP'})
base8 = base8.rename(columns={'DDD.7': 'DDD', 'FONE.7': 'FONE', 'TIPO-FONE.7': 'TIPO-FONE','RANKING.7': 'RANKING', 'SCORE.7': 'SCORE', 'POSSUI-WHATSAPP.7': 'POSSUI-WHATSAPP'})

base = pd.concat([base1, base2, base3, base4, base5, base6, base7, base8])

bas = base.dropna(subset=['DDD'])
bas['CHAVE'] = bas['CPF/CNPJ'].astype(str) + '-' + bas['DDD'].astype(str) + bas['FONE'].astype(str)

conf = pd.merge(bas, df_num1, on='CHAVE', how='left')
conf = conf.drop_duplicates(subset=['CHAVE'])

conf = conf[['NOME','CPF/CNPJ_x','DDD','FONE','TIPO-FONE','RANKING','SCORE','POSSUI-WHATSAPP','CHAVE','ATIVO']]
conf['ATIVO'] = conf['ATIVO'].fillna('')
conf1 = conf.loc[conf['ATIVO'] != 'NÃO']
conf1['TIPO'] = np.where(conf1['TIPO-FONE'] == '1', 'RESIDENCIAL', 'MOVEL')
conf1['WPP'] = np.where(conf1['POSSUI-WHATSAPP'] == '1', 'SIM', 'NÃO')
conf1['TELEFONE'] = conf1['DDD'].astype(str) + conf1['FONE'].astype(str)
conf1['OBSERVAÇÃO'] = 'LEMIT '+ datetime.now().strftime('%d-%m-%Y') + ' | RANKING : ' + conf1['RANKING'] + ' | SCORE : ' + conf1['SCORE'] + ' | WHATSAPP : ' + conf1['WPP']
conf1['STATUS'] = 'ATIVO'
conf1['RETORNO URA'] = ''
conf1['AUTORIZADO'] = 1
conf1 = conf1.rename(columns={'CPF/CNPJ_x': 'CPF/CNPJ','POSSUI-WHATSAPP':'WHATSAPP'})
arq_import = conf1[['CPF/CNPJ','TELEFONE','TIPO','OBSERVAÇÃO','STATUS','RETORNO URA','WHATSAPP','AUTORIZADO']]
conf2 = conf1[['NOME','CPF/CNPJ','TELEFONE','RANKING','SCORE','TIPO','OBSERVAÇÃO','STATUS','ATIVO','RETORNO URA','WHATSAPP','AUTORIZADO']]

arq_import.to_excel(f"LEMIT_HIG_(CREDOR)_{datetime.now().strftime('%d-%m-%Y')}.xlsx", index=False)
conf2.to_excel(f"Higienização_(CREDOR)_{datetime.now().strftime('%d-%m-%Y')}.xlsx", index=False)